### ISSUE TITLE
Game Mechanics:  Deal

### ISSUE THREAD

**Issue by kjrinuk** [kjrinuk/BlackJack#10]
As a **player** I can **start the round** by pushing a button **so that I can see the cards being dealt**

### **Acceptance Criteria:**
* Deal button clicked:  Cards dealt to player and dealer
* Cards dealt to player:  both cards revealed
* Cards dealt to dealer:  first card revealed, second card hidden

### Task
- [ ] 2 Cards dealt for player showing both players cards
- [ ] Dealer has the first card hidden and the second showing
- [ ] Check for BlackJack for player and Dealer

### Resources:
* [Style-guides and template for a user story](agile-user-story.md)
* ["Advantages of the "As a user, I want" user story template."](http://www.mountaingoatsoftware.com/blog/advantages-of-the-as-a-user-i-want-user-story-template)
* [Scrum guide](http://scrumguides.org/scrum-guide.html)
