### ISSUE TITLE
Game Mechanics: Reset

### ISSUE THREAD

**Issue by ErfanNajimi** [kjrinuk/BlackJack#13]
As a **player** I can **reset the scores at any point** so that **I can achieve a better score and start afresh.**

### **Acceptance Criteria:**
* Acceptance Criteria 1: Clear and visible reset or restart button
* Acceptance Criteria 2: Once clicked, should alert the user and prompt them to deal
* Acceptance Criteria 3: Resets the scores in scoring system in place

### Task
- [ ] Task 1 - Create button for reset / restart
- [ ] Task 2 - Add JS functionality to reset cards and scores
- [ ] Task 3 - Add JS functionality to prompt user to hit 'deal'

**Comment by Damitwhy** [comment]
reset? both players and Dealer/Bankers score? hmmm what does the banker/dealer say about that? Page refresh could do the same thing...
