### ISSUE TITLE
User story: Gambling addict

### ISSUE THREAD

**Issue by Damitwhy** [kjrinuk/BlackJack#15]
As a **Gambling Addict** I can **I've access to gambling advice as external link ** so that **I can remain aware of my options**

### **Acceptance Criteria:**
* Our players should be able to press a button to access safe gambling advice
* That our game does not allow real money gaming
* if chips: chip representation is as unreal as images will allow but still remaining as close to representation as possible

### Task
- [x] use chip images that give cartoon like representation
- [x] provide a link to a safe gambling advice sites
- [x] recognise out user base and their needs concerning gambling habits

### Resources:
* [Style-guides and template for a user story](agile-user-story.md)
* ["Advantages of the "As a user, I want" user story template."](http://www.mountaingoatsoftware.com/blog/advantages-of-the-as-a-user-i-want-user-story-template)
* [Scrum guide](http://scrumguides.org/scrum-guide.html)
