### ISSUE TITLE
Game Mechanics: cash out

### ISSUE THREAD

**Issue by ErfanNajimi** [kjrinuk/BlackJack#16]
Note: CASH OUT replaces any RESET / RESTART button already in place.

As a **player** I can **choose to cash out my virtual winnings after playing some number of rounds** so that **I can *

### **Acceptance Criteria:**
* Acceptance Criteria 1: Keep track of current winnings
* Acceptance Criteria 2: Have the option to cash out at any point (even £0)
* Acceptance Criteria 3: Give summary of game after cash out

### Task
- [ ] Task 1 - Use a var & func in JS to keep track of winnings amount
- [ ] Task 2 - Create cash out button
- [ ] Task 3 - Add functionality to button so that summary of game is shown to player after cash out
