### ISSUE TITLE
User Story: Who's made this Site?

### ISSUE THREAD

**Issue by Damitwhy** [kjrinuk/BlackJack#17]
As a **Player** I want to **KNow who has produced this site** so that **i can trust there is some one held responsible with my game play **

### **Acceptance Criteria:**
* Developers details visible to any one who uses game
* Write developers names in JS code and on page tags
* added source links where applicable 

### Task
- [ ] Own code with names of our development team or company
- [ ] adopt a free licensing certification like MIT
- [ ] added source links where applicable 

### Resources:
* [Style-guides and template for a user story](agile-user-story.md)
* ["Advantages of the "As a user, I want" user story template."](http://www.mountaingoatsoftware.com/blog/advantages-of-the-as-a-user-i-want-user-story-template)
* [Scrum guide](http://scrumguides.org/scrum-guide.html)
