### ISSUE TITLE
Game Mechanics: betting with chips

### ISSUE THREAD

**Issue by ErfanNajimi** [kjrinuk/BlackJack#18]
As a **player** I can **use chips to see current cash in the bank and choose how much to bet each round** so that **I can have a more interactive game then resembles blackjack in a casino.**

### **Acceptance Criteria:**
* Acceptance Criteria 1: Have visual representations of the chips
* Acceptance Criteria 2: Be able to click on the chips (or move them around if possible)
* Acceptance Criteria 3: Bet using chips at the start of the round

### Task
- [ ] Task 1: Find images for chips
- [ ] Task 2: Use JS to dynamically code functionality which shows number of chips depending on cash available
- [ ] Task 3: Make sure to reset initial chip amount at the start of the game (after player resets/restarts)
