### ISSUE TITLE
User Story: When do i stop?

### ISSUE THREAD

**Issue by Damitwhy** [kjrinuk/BlackJack#19]
As a **Player** I can get carried away in game play ** i want to know when i've been on too long ** so that ** I wont miss life obligations **

### **Acceptance Criteria:**
* A way to let the player know how much time is spent on game
* visible to player at a glance
* audio ping to drawn players attention to time of session

### Task
- [x] some king of timer
- [ ] some kind of notification
- [x] represented on table

### Resources:
* [Style-guides and template for a user story](agile-user-story.md)
* ["Advantages of the "As a user, I want" user story template."](http://www.mountaingoatsoftware.com/blog/advantages-of-the-as-a-user-i-want-user-story-template)
* [Scrum guide](http://scrumguides.org/scrum-guide.html)

**Comment by Damitwhy** [comment]
Could do this

**Comment by Damitwhy** [comment]
There is a timer now starts on page load I've had to place it bottom left of page so it does not obscure as pages is responsive
