### ISSUE TITLE
Game Mechanics:  Deal to dealer law implementation

### ISSUE THREAD

**Issue by kjrinuk** [kjrinuk/BlackJack#21]
As a **player** I can **stand and watch the dealer deal** so that **I can win a picture of Erfan**

### **Acceptance Criteria:**
* Player has "stood":  Dealer deals to itself until it is greater than 17 and greater than or equal to players score and not bust
* :
* :

### Task
- [x] Dealer deals to itself once player stands and ...
- [x] Dealer deals until equal to or greater than players score and ...
- [x] Dealer deals until dealer score is greater than 16 and not bust

### Resources:
* [Style-guides and template for a user story](agile-user-story.md)
* ["Advantages of the "As a user, I want" user story template."](http://www.mountaingoatsoftware.com/blog/advantages-of-the-as-a-user-i-want-user-story-template)
* [Scrum guide](http://scrumguides.org/scrum-guide.html)

**Comment by Damitwhy** [comment]
done
