### ISSUE TITLE
User Story : Website Structure

### ISSUE THREAD

**Issue by Damitwhy** [kjrinuk/BlackJack#22]
As a **Developer** I can **create a site structure** so that **for read ability and collaboration our site collaborators know where files and folders and sections of html can be found**

### **Acceptance Criteria:**
* Standard file folders in place, such as assets, images, js code, header, footer main inside body

### Task
- [x] skeleton html and boiler plate
- [x] create file system
- [x] create files as place holders before work begins so developers have a basic structure in place to base every thing on

### Resources:
* [Style-guides and template for a user story](agile-user-story.md)
* ["Advantages of the "As a user, I want" user story template."](http://www.mountaingoatsoftware.com/blog/advantages-of-the-as-a-user-i-want-user-story-template)
* [Scrum guide](http://scrumguides.org/scrum-guide.html)
