### ISSUE TITLE
User story: KanBan Board

### ISSUE THREAD

**Issue by Damitwhy** [kjrinuk/BlackJack#23]
As a **collaborator** I can **see a Kanban board** so that ** I can find what work needs doing, who's doing it and if I'm selected as participant **

### **Acceptance Criteria:**
* Kanban Board created
* Collaborators invited
* collaborators can access and edit the board

### Task
- [ ] Create Kanban in projects on Github
- [ ] Invite all collaborators to project
- [ ] Set collaborators privileges  

### Resources:
* [Style-guides and template for a user story](agile-user-story.md)
* ["Advantages of the "As a user, I want" user story template."](http://www.mountaingoatsoftware.com/blog/advantages-of-the-as-a-user-i-want-user-story-template)
* [Scrum guide](http://scrumguides.org/scrum-guide.html)
