### ISSUE TITLE
MoSCoW priority list

### ISSUE THREAD

**Issue by Damitwhy** [kjrinuk/BlackJack#35]
As a **product owner** I can **see a MoSCoW priority list** so that **I know which features are going to be created which aren't and I can negotiate features that the Board of shareholders require **

### **Acceptance Criteria:**
* Listing Features taken from user stories
* listing Features of site structure
* prioritising by taking Value added, difficulty in creation and evaluating if it should go in either Won't, Should, Could or Must categories.

### Task
- [x] stand up to discuss features
- [x] manually adding features to table discuss how difficult each feature is
- [x] assigning the difficulty number between 1 and 5, 5 being most difficult
- [x] assigning the Value added and number between 1 and 5, 5 being most value
- [x] decide which features give the most value over least difficulty and prioritise those over features giving less value over more difficulty.

### Resources:
* [Style-guides and template for a user story](agile-user-story.md)
* ["Advantages of the "As a user, I want" user story template."](http://www.mountaingoatsoftware.com/blog/advantages-of-the-as-a-user-i-want-user-story-template)
* [Scrum guide](http://scrumguides.org/scrum-guide.html)

**Comment by Damitwhy** [comment]
All features discussed first morning of Hackathon.
