### ISSUE TITLE
Game Mechanics: Hit

### ISSUE THREAD

**Issue by ErfanNajimi** [kjrinuk/BlackJack#9]
As a **player** I can **press the hit button to deal more cards** so that **I can achieve a closer value to 21 with the cards received and hopefully 'hit' blackjack!**

### **Acceptance Criteria:**
* Acceptance Criteria 1: Visible 'hit' button which is clickable
* Acceptance Criteria 2: Once clicked, new cards should be dealt to the player
* Acceptance Criteria 3: When the hit option is available, I should not be able to click the deal button
* Acceptance Criteria 4: Once bust or achieved blackjack, stop the option to getting hitting button

### Tasks
- [ ] Task 1: Create button tag with appropriate design
- [ ] Task 2: Add JS functionality to deal an extra card to player
- [ ] Task 3: Prevent user from hitting hit when appropriate
